#!/bin/sh

grep -cq /compat/linux/ /etc/fstab > /dev/null 2>&1
if [ $? -gt 0 ]; then
	_DETAIL "Updated /etc/fstab for sublime text 4"

	printf '# sublime text\n' >> /etc/fstab
	printf 'devfs      /compat/linux/dev      devfs      rw,late                    0  0' >> /etc/fstab
	printf 'tmpfs      /compat/linux/dev/shm  tmpfs      rw,late,size=1g,mode=1777  0  0' >> /etc/fstab
	printf 'fdescfs    /compat/linux/dev/fd   fdescfs    rw,late,linrdlnk           0  0' >> /etc/fstab
	printf 'linprocfs  /compat/linux/proc     linprocfs  rw,late                    0  0' >> /etc/fstab
	printf 'linsysfs   /compat/linux/sys      linsysfs   rw,late                    0  0' >> /etc/fstab
else
	_WARN "/etc/fstab is already setup for sublime text 4"
fi
