#!/bin/sh

cfg feature:.


_vscode_install_extensions() {
	if [ -z "$_FEATURE_VSCODE_EXTENSIONS" ]; then
		log_warn "_FEATURE_VSCODE_EXTENSIONS is empty"
		return 1
	fi

	local vscode_extension
	for vscode_extension in $(printf '%s\n' "$_FEATURE_VSCODE_EXTENSIONS"); do
		$conf_dev_vscode_executable --install-extension $vscode_extension > /dev/null 2>&1 || log_warn "install $vscode_extension failed"
	done
}

_vscode_install_extensions
