#!/bin/sh

lib net/download.sh
lib extract.sh

spring_cli_version=4.0.0

_download_fetch https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-cli/$spring_cli_version/spring-boot-cli-$spring_cli_version-bin.tar.gz

spring_cli_contents=$(_mktemp_options=d _mktemp_mktemp)

_cleanup_spring() {
	rm -rf $spring_cli_contents
}

_extract_extract $download_file $spring_cli_contents
exit_defer _cleanup_spring

local _dest="$TARGET_APP_PATH/tools/$feature_name/spring-boot-cli.jar"
mkdir -p "$(dirname $_dest)"
mv $spring_cli_contents/spring-${spring_cli_version}/lib/spring-boot-cli-${spring_cli_version}.jar "$_dest"
_install_record_path "$_dest"
