#!/bin/sh

lib ./setup/console.sh

for _USER in $($_CONF_GNU_GREP -P '^(wheel|operator|video):' /etc/group | cut -f4 -d':' | tr ',' '\n' | sort -u); do
	_HOME=$(grep "^$_USER:" /etc/passwd | cut -f6 -d:)
	_SHELL=zsh _console_conf
done
