#!/bin/sh

_extension_find_default -exec $GNU_SED -i '/^\/\/$/d' {} +

_extension_find_default -exec $GNU_SED -i '/^\/\*\* \*\/$/d' {} +

_extension_find_default -exec $GNU_SED -i 's/\/\*\* \*\///g' {} +


