#!/bin/sh

lib extract.sh
lib net/download.sh

windsurf_version=1.9566.11
windsurf_sha_version=8911695f6454083fd48c3422f4736eb88053357c
windsurf_filename=Windsurf-linux-x64-$windsurf_version.tar.gz
windsurf_installation_path=/opt/windsurf

_install_windsurf() {
    _download_fetch https://windsurf-stable.codeiumdata.com/linux-x64/stable/$windsurf_sha_version/$windsurf_filename

    clean=$windsurf_installation_path _extract_extract $download_file $windsurf_installation_path

    mv $windsurf_installation_path/Windsurf/* $windsurf_installation_path
    rm -rf $windsurf_installation_path/Windsurf

    ln -sf $windsurf_installation_path/windsurf $APP_PLATFORM_BIN_PATH/windsurf
}

_is_windsurf_installed() {
    [ ! -e $APP_PLATFORM_BIN_PATH/windsurf ] && return 1
    
    local installed_windsurf_version=$(jq -r '.windsurfVersion' $windsurf_installation_path/resources/app/product.json)
    log_detail "windsurf is installed: $installed_windsurf_version"

    [ "$windsurf_version" = "$installed_windsurf_version" ]
}

if ! _is_windsurf_installed; then
    _install_windsurf
else
    log_detail "windsurf is already installed"
fi
