_proxy_start() {
	$_CONF_REMOTE_SERVICE_CMD $_CONF_REMOTE_PROXY_SERVICE_NAME $_CONF_REMOTE_SERVICE_START_ACTION
}

_proxy_stop() {
	$_CONF_REMOTE_SERVICE_CMD $_CONF_REMOTE_PROXY_SERVICE_NAME $_CONF_REMOTE_SERVICE_STOP_ACTION
}
