lib net/firewall.sh

_stunnel_start() {
	_firewall_update_table $_CONF_REMOTE_STUNNEL_TABLE_NAME $1

	$_CONF_REMOTE_SERVICE_CMD $_CONF_REMOTE_STUNNEL_SERVICE_NAME $_CONF_REMOTE_SERVICE_START_ACTION
	$_CONF_REMOTE_SERVICE_CMD $_CONF_REMOTE_PROXY_SERVICE_NAME $_CONF_REMOTE_SERVICE_START_ACTION
}

_stunnel_stop() {
	_firewall_flush_table $_CONF_REMOTE_STUNNEL_TABLE_NAME

	$_CONF_REMOTE_SERVICE_CMD $_CONF_REMOTE_STUNNEL_SERVICE_NAME $_CONF_REMOTE_SERVICE_STOP_ACTION
	$_CONF_REMOTE_SERVICE_CMD $_CONF_REMOTE_PROXY_SERVICE_NAME $_CONF_REMOTE_SERVICE_STOP_ACTION
}
