_user_callback() {
	_require "$_OPTN_REMOTE_USER_CALLBACK_CMD" _OPTN_REMOTE_USER_CALLBACK_CMD
	_require "$_OPTN_REMOTE_USER_CALLBACK_TIMEOUT" _OPTN_REMOTE_USER_CALLBACK_TIMEOUT

	_INFO "running $_OPTN_REMOTE_USER_CALLBACK_CMD ($@) with timeout: $_OPTN_REMOTE_USER_CALLBACK_TIMEOUT"
	timeout $_OPTN_REMOTE_USER_CALLBACK_TIMEOUT $_OPTN_REMOTE_USER_CALLBACK_CMD "$@"

	local status=$?

	_INFO "running $_OPTN_REMOTE_USER_CALLBACK_CMD ($@) with timeout: $_OPTN_REMOTE_USER_CALLBACK_TIMEOUT -> $status"
	return $status
}
