#!/bin/sh

lib extract.sh
lib net/download.sh

readonly ANDROID_STUDIO_VERSION="2025.3.1.8"
readonly ANDROID_STUDIO_SUB_VERSION="panda1-patch1"
readonly ANDROID_STUDIO_INSTALL_PATH=/opt/Google/AndroidStudio

_download_fetch "https://dl.google.com/android/studio/ide-zips/${ANDROID_STUDIO_VERSION}/android-studio-${ANDROID_STUDIO_SUB_VERSION}-linux.tar.gz"

clean=1 _extract_extract $download_file $ANDROID_STUDIO_INSTALL_PATH
mv $ANDROID_STUDIO_INSTALL_PATH/android-studio/* $ANDROID_STUDIO_INSTALL_PATH/
rm -rf $ANDROID_STUDIO_INSTALL_PATH/android-studio

ln -sf $ANDROID_STUDIO_INSTALL_PATH/bin/studio /usr/local/bin/android-studio
