#!/bin/sh

lib net/download.sh

REPO="lightpanda-io/browser"
API_URL="https://api.github.com/repos/$REPO/releases/latest"

_download_lightpanda() {
    local download_url=$(curl -s $API_URL | jq -r '.assets[] | select(.name | test(".*x86_64.*macos.*")) | .browser_download_url')

    [ -z "$download_url" ] && {
        log_warn "no 64-bit Apple executable found in the latest release."
        return 1
    }

    _download_fetch "$download_url"
}

_install_lightpanda() {
    _install_file_chmod=755 _download_install_file $BIN_PATH/lightpanda
}

which lightpanda > /dev/null 2>&1 || {
    _download_lightpanda && _install_lightpanda
}
