#!/bin/sh

lib net/download.sh
lib io/write.sh


_intellij_build() {
    _defer _cleanup_intellij_patch

    _download 'https://bz-attachments.freebsd.org/attachment.cgi?id=258323' 'intellij-2024.3.3.patch' || error "intellij-port does NOT exist"

    pkg _INFO intellij > /dev/null 2>&1 && _sudo pkg remove -y intellij

    cd /usr/ports/java/intellij

    _INFO "Applying patch to intellij"
    _sudo git apply $_DOWNLOADED_FILE

    _INFO "Building intellij"
    BATCH=yes sudo_options="--preserve-env=BATCH" _sudo make install || _ERROR "Unable to build intellij"
}

_intellij_init_ports() {
    [ ! -e /usr/ports/.git ] && {
        _sudo git clone https://git.FreeBSD.org/ports.git /usr/ports || _ERROR "Unable to setup ports"
        return
    }

    _sudo git -C /usr/ports reset --hard HEAD

    _sudo git -C /usr/ports pull
}

_cleanup_intellij_patch() {
    _INFO "Cleaning up intellij patch"
    cd /usr/ports/java/intellij

    BATCH=yes sudo_options="--preserve-env=BATCH" _sudo make clean
    _sudo rm -rf work
    _sudo git reset --hard HEAD
}

_intellij_configure() {
    _sudo rm -f /usr/local/share/intellij/bin/idea.vmoptions

    printf '%s\n' '-Dawt.useSystemAAFontSettings=on' | _append /usr/local/share/intellij/bin/idea.vmoptions
    printf '%s\n'  '-Dswing.aatext=true' | _append /usr/local/share/intellij/bin/idea.vmoptions
    printf '%s\n'  '-Dsun.java2d.xrender=true' | _append /usr/local/share/intellij/bin/idea.vmoptions

    _sudo $_CONF_GNU_SED -i 's/^-Dsun.java2d.xrender=false/-Dsun.java2d.xrender=true/' /usr/local/share/intellij/bin/idea64.vmoptions
    printf '%s\n'  '-Dawt.useSystemAAFontSettings=on' | _append /usr/local/share/intellij/bin/idea64.vmoptions
    printf '%s\n'  '-Dswing.aatext=true' | _append /usr/local/share/intellij/bin/idea64.vmoptions
}

_intellij_init_ports
_intellij_build
_intellij_configure
