#!/bin/bash

for f in $(find /media/output-files/links -type l)
do
  	_INFO $f
        t=$(printf '%s' $f | sed -e "s/links\/media\/pictures\/photos\///")

        tp=$(dirname $t)
       	if [ ! -e "$tp" ]
       	then
               	_WARN "$tp does not exist"
       	else
		if [ -e "$tp" ]
			shash=$(basename "$f" -l | awk -F ' ' {'print$11'})
			thash=$(basename "$tp" -l | awk -F ' ' {'print$11'})

			if [ "$shash" = "$thash" ]
			then
				_WARN "Not moving as source and target are identical"
			else
				_WARN "Problem, target already exists, but for a different file"
			fi
		else
	                _INFO "mv $f $tp -i"
		fi
        fi
done

