#!/bin/bash

for f in $(find /media/output-files/movie -type l)
do
  	_INFO $f
        t=$(printf '%s' $f | sed -e "s/movie\///")

        tp=$(dirname $t)
       	if [ ! -e "$tp" ]
       	then
		mkdir -p "$tp"
                mv "$f" "$tp" -i
       	else
                mv "$f" "$tp" -i
        fi
done

