#!/bin/sh


lib net/download.sh
lib extract.sh
lib io/link.sh

: ${_CONF_DEV_DBEAVER_EDITION:=ce}

_dbeaver_install() {
    _DBEAVER_INSTALL_PATH=/usr/local/dbeaver/community

    _download "https://dbeaver.io/files/dbeaver-${_CONF_DEV_DBEAVER_EDITION}-latest-linux.gtk.$_ARCHITECTURE-nojdk.tar.gz"

    _CLEAN=$_DBEAVER_INSTALL_PATH _SUDO_REQUIRED=1 _extract "$_DOWNLOADED_FILE" "$_DBEAVER_INSTALL_PATH"

    $_link $_CONF_BIN_PATH/dbeaver $_DBEAVER_INSTALL_PATH/dbeaver
    $_SUDO_CMD chmod +x $_CONF_BIN_PATH/dbeaver
}

_dbeaver_platform_check() {
    case $_SUB_PLATFORM in
        Gentoo)
            _WARN "OS Package is available"
            return 1
            ;;
    esac
}

_dbeaver_architecture_check() {
    case $_ARCHITECTURE in
        amd64|aarch64)
            ;;
        *)
            _WARN "Unsupported architecture: $_ARCHITECTURE"
            return 1
            ;;
    esac
}

_dbeaver_platform_check && _dbeaver_architecture_check && _dbeaver_install
