lib gsettings.sh

_PLUGIN_CONFIGURATION_PATH=~/.config
_PLUGIN_CONFIGURATION_PATH_IS_DIR=1
_PLUGIN_CONFIGURATION_PATH_IS_SKIP_PREPARE=1
_PLUGIN_NO_ROOT_USER=1

_GSETTINGS_MELD_KEY=org.gnome.meld

case $_PLATFORM in
Apple)
	unset _PLUGIN_CONFIGURATION_PATH _PLUGIN_CONFIGURATION_PATH_IS_DIR _PLUGIN_CONFIGURATION_PATH_IS_SKIP_PREPARE
	;;
esac

_CONFIGURE_MELD_BACKUP() {
	_gsettings_dump $_GSETTINGS_MELD_KEY
}

_CONFIGURE_MELD_RESTORE() {
	_gsettings_restore $_GSETTINGS_MELD_KEY
}

_CONFIGURE_MELD_CLEAR() {
	:
}
