#!/bin/sh

lib net/download.sh
lib io/write.sh


_intellij_build() {
    exit_defer _cleanup_intellij_patch

    _download_fetch 'https://bz-attachments.freebsd.org/attachment.cgi?id=258323' 'intellij-2024.3.3.patch' || exit_with_error "intellij-port does NOT exist"

    pkg info intellij > /dev/null 2>&1 && sudo_run pkg remove -y intellij

    cd /usr/ports/java/intellij

    log_info "applying patch to intellij"
    sudo_run git apply $download_file

    log_info "building intellij"
    BATCH=yes sudo_options="--preserve-env=BATCH" sudo_run make install || exit_with_error "unable to build intellij"
}

_intellij_init_ports() {
    [ ! -e /usr/ports/.git ] && {
        sudo_run git clone --depth 1 https://git.FreeBSD.org/ports.git /usr/ports || exit_with_error "unable to setup ports"
        return
    }

    sudo_run git -C /usr/ports reset --hard HEAD

    sudo_run git -C /usr/ports pull
}

_cleanup_intellij_patch() {
    log_info "cleaning up intellij patch"
    cd /usr/ports/java/intellij

    BATCH=yes sudo_options="--preserve-env=BATCH" sudo_run make clean
    sudo_run rm -rf work
    sudo_run git reset --hard HEAD
}

_intellij_configure() {
    sudo_run rm -f /usr/local/share/intellij/bin/idea.vmoptions

    printf '%s\n' '-Dawt.useSystemAAFontSettings=on' | _append /usr/local/share/intellij/bin/idea.vmoptions
    printf '%s\n'  '-Dswing.aatext=true' | _append /usr/local/share/intellij/bin/idea.vmoptions
    printf '%s\n'  '-Dsun.java2d.xrender=true' | _append /usr/local/share/intellij/bin/idea.vmoptions

    sudo_run $GNU_SED -i 's/^-Dsun.java2d.xrender=false/-Dsun.java2d.xrender=true/' /usr/local/share/intellij/bin/idea64.vmoptions
    printf '%s\n'  '-Dawt.useSystemAAFontSettings=on' | _append /usr/local/share/intellij/bin/idea64.vmoptions
    printf '%s\n'  '-Dswing.aatext=true' | _append /usr/local/share/intellij/bin/idea64.vmoptions
}

log_warn "this is unmaintained"
