#!/bin/sh

if [ -n "$_INSTALLER" ]; then
	log_warn "using $_INSTALLER to install this package"
	return
fi

_GLAB_VERSION=1.22.0
_GLAB_ARCHITECTURE=Windows_x86_64

_GLAB_FILENAME=glab_${_GLAB_VERSION}_${_GLAB_ARCHITECTURE}.zip

_download_fetch https://github.com/profclems/glab/releases/download/v$_GLAB_VERSION/$_GLAB_FILENAME $_GLAB_FILENAME

unzip $_GLAB_FILENAME >/dev/null 2>&1

mv bin/glab.exe $APP_PLATFORM_BIN_PATH

rm -rf $_GLAB_FILENAME CHANGELOG.md LICENSE README.md
