#!/bin/sh

_ollama_is_supported() {
    lspci | $_CONF_GNU_GREP -P '(AMD|NVIDIA)' | $_CONF_GNU_GREP -Picqm1 '(display|graphics)'
}

_ollama_install() {
    which ollama > /dev/null 2>&1 || {
        _DETAIL "Installing ollama"
        curl -fsSL https://ollama.com/install.sh | sh
    }
}

_ollama_is_supported || {
  _WARN "Ollama does not appear to support this hardware"
  exit 0
}

_ollama_install
