#!/bin/sh

lib net/download.sh

_SIKULIX_IDE_VERSION=2.0.5
_SIKULIX_JAR_FILENAME=sikulixide-${_SIKULIX_IDE_VERSION}-lux.jar
_download https://launchpad.net/sikuli/sikulix/$_SIKULIX_IDE_VERSION/+download/$_SIKULIX_JAR_FILENAME

_download_install_file ${_CONF_APPLICATION_LIBRARY_PATH}/sikulix-ide.jar

for _USER in $($_CONF_GNU_GREP -P '^(wheel|operator|video):' /etc/group | cut -f4 -d':' | tr ',' '\n' | sort -u | grep -v root); do
  _SUDO_USER=$_USER _sudo mkdir -p /home/$_USER/.Sikulix/SikulixLibs
  _SUDO_USER=$_USER _sudo rm -f /home/$_USER/.Sikulix/SikulixLibs/libJXGrabKey.so

  _SUDO_USER=$_USER _sudo ln -s /usr/local/lib/libJXGrabKey.so /home/$_USER/.Sikulix/SikulixLibs/libJXGrabKey.so
done
