#!/bin/sh

lib time.sh

which az >/dev/null 2>&1 && {
    _timeout $_CONF_DEV_AZURE_UPGRADE_TIMEOUT "Microsoft Azure conf, enable auto upgrade" az config set auto-upgrade.enable=yes
    _timeout $_CONF_DEV_AZURE_UPGRADE_TIMEOUT "Microsoft Azure cli upgrade" az upgrade -y

    _timeout $_CONF_DEV_AZURE_LOGIN_TIMEOUT "Microsoft Azure account clear" $_SUDO_NORMAL_USER_CMD az account clear
    _timeout $_CONF_DEV_AZURE_LOGIN_TIMEOUT "Microsoft Azure login" $_SUDO_NORMAL_USER_CMD az login -o $_CONF_DEV_AZURE_OUTPUT_FORMAT
}
