#!/bin/sh

pciconf -lv | grep -cqm1 'Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller' && {
  log_warn "legacy opengl detected, setting LIBGL_ALWAYS_SOFTWARE=1 for ghostty"
  grep -cqm1 'setenv' /etc/login.conf && {
  	grep LIGGL_ALWAYS_SOFTWARE=1 /etc/login.conf || {
  		$GNU_SED -i 's/setenv=/setenv=LIBGL_ALWAYS_SOFTWARE=1,/' /etc/login.conf
  		cap_mkdb /etc/login.conf
  	}
  }
}

true
