_EXPECT_BOOTSTRAP() {
	_EXPECT_BOOTSTRAP_IS_EXPECT_AVAILABLE || {
		_PACKAGE_INSTALL $EXPECT_PACKAGE
		_EXPECT_BOOTSTRAP_IS_EXPECT_AVAILABLE || EXPECT_DISABLED=1
	}
}

_EXPECT_BOOTSTRAP_IS_EXPECT_AVAILABLE() {
	which expect >/dev/null 2>&1
}

_EXPECT_INSTALL() {
	$1 >/dev/null 2>&1
}

_EXPECT_UNINSTALL() {
	_WARN "expect uninstall - Not implemented"
}

_EXPECT_IS_INSTALLED() {
	return 1
}

_EXPECT_IS_FILE() {
	return 0
}
