#!/bin/sh

cfg feature:.

_detect_secrets_venv_install() {
    mkdir -p $(dirname $conf_dev_detect_secrets_venv)

    python -m venv $conf_dev_detect_secrets_venv
    . $conf_dev_detect_secrets_venv/bin/activate
    pip install $conf_dev_detect_secrets_python_artifact

    deactivate
}

_detect_secrets_venv_exists() {
    [ ! -e $conf_dev_detect_secrets_venv/bin/activate ] && return 1

    [ -e $conf_dev_detect_secrets_venv/bin/detect-secrets ]
 }
 
if ! _detect_secrets_venv_exists; then
    log_detail "installing detect-secrets venv"
    _detect_secrets_venv_install
else
    log_detail "detect-secrets venv already exists"
fi
