#!/bin/sh

cfg feature:.

_detect_secrets_venv_install() {
    command -v python > /dev/null 2>&1 || {
        log_warn 'python not detected'
        return 1
    }

    command -v pip > /dev/null 2>&1 || {
        log_warn 'pip not detected'
        return 1
    }

    mkdir -p $(dirname $conf_dev_detect_secrets_venv)

    python -m venv $conf_dev_detect_secrets_venv
    . $conf_dev_detect_secrets_venv/bin/activate
    pip install $conf_dev_detect_secrets_python_artifact

    deactivate

    _install_record_dir "$conf_dev_detect_secrets_venv"
}

_detect_secrets_venv_exists() {
    [ ! -e $conf_dev_detect_secrets_venv/bin/activate ] && return 1
    [ -e $conf_dev_detect_secrets_venv/bin/detect-secrets ]
}

if ! _detect_secrets_venv_exists; then
    log_detail "installing detect-secrets venv"
    _detect_secrets_venv_install
else
    log_detail "detect-secrets venv already exists"
fi
