#!/bin/sh

cfg feature:.


_vscodium_install_extensions() {
	if [ -z "$_FEATURE_VSCODIUM_EXTENSIONS" ]; then
		_WARN "_FEATURE_VSCODIUM_EXTENSIONS is empty"
		return 1
	fi

	local vscodium_extension
	for vscodium_extension in $(printf '%s\n' "$_FEATURE_VSCODIUM_EXTENSIONS"); do
		$_CONF_DEV_VSCODIUM_EXECUTABLE --install-extension $vscodium_extension > /dev/null 2>&1 || _WARN "Install $vscodium_extension failed"
	done
}

_vscodium_install_extensions
