#!/bin/sh

lib io/link.sh

case $_SUB_PLATFORM in
    Ubuntu)
        if [ "$_ARCHITECTURE" = "arm64" ]; then
            _POSTMAN_INSTALL_PATH=/usr/local/postman

            _download "https://dl.pstmn.io/download/latest/linux_arm64"

            _CLEAN=$_POSTMAN_INSTALL_PATH _SUDO_REQUIRED=1 _extract "$_DOWNLOADED_FILE" "$_POSTMAN_INSTALL_PATH"
            _link $_CONF_BIN_PATH/Postman $_POSTMAN_INSTALL_PATH/app/Postman
            $_SUDO_CMD chmod +x $_CONF_BIN_PATH/Postman
        else
            snap install postman
        fi
        ;;
    *)
        _WARN "Unsupported distribution, $_SUB_PLATFORM"
        ;;
esac
