#!/bin/sh

ghostty_executable=$(which ghostty 2>/dev/null) && {
  ln -sf $ghostty_executable /usr/local/bin/x-terminal-emulator
  ln -sf $ghostty_executable /usr/local/bin/terminal
}

inxi -G -y 1 --no-host 2>/dev/null | grep -cqm1 'compat-v: 4.2' && {
  log_warn "legacy opengl detected, setting LIBGL_ALWAYS_SOFTWARE=1 for ghostty"
  grep -q "^LIBGL_ALWAYS_SOFTWARE=" /etc/environment || printf "LIBGL_ALWAYS_SOFTWARE=1\n" >> /etc/environment
}

true
