#!/bin/sh

lib net/download.sh
lib extract.sh

_DBEAVER_CONTENTS=$(_mktemp_options=d _mktemp_mktemp)

_cleanup_dbeaver() {
	rm -rf $_DBEAVER_CONTENTS
}

_download_fetch https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
_extract_extract $download_file $_DBEAVER_CONTENTS
exit_defer _cleanup_dbeaver

mkdir -p $APP_LIBRARY_PATH/feature/$_FEATURE_NAME
mv $_DBEAVER_CONTENTS/dbeaver/* $APP_LIBRARY_PATH/feature/$_FEATURE_NAME
