#!/bin/sh

lib net/download.sh
lib extract.sh

_kiro_install() {
    kiro_url="https://desktop-release.q.us-east-1.amazonaws.com/latest/kirocli-$APP_PLATFORM_ARCHITECTURE-linux.zip"
    _download_fetch $kiro_url

    cd /tmp
    _extract_extract $download_file /tmp/kirocli
    exit_defer rm -rf /tmp/kirocli

    mv /tmp/kirocli/kirocli/bin/kiro-cli /tmp/kirocli/kirocli/bin/kiro-cli-chat /tmp/kirocli/kirocli/bin/kiro-cli-term \
        $APP_PLATFORM_BIN_PATH/
}

[ -e $APP_PLATFORM_BIN_PATH/kiro-cli ] || _kiro_install
