#!/bin/sh


_is_passff_host_installed() {
  [ -d "/etc/opt/chrome/native-messaging-hosts" ] ||
  [ -d "/usr/lib/mozilla/native-messaging-hosts" ] ||
  [ -d "/etc/vivaldi/native-messaging-hosts" ] ||
  [ -d "/usr/lib/librewolf/native-messaging-hosts" ]
}

_install_passff_host() {
  curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- firefox
}

if _is_passff_host_installed; then
  _install_passff_host
fi
