lib net/download.sh

GOOGLE_ANTIGRAVITY_INSTALL_PATH=/opt/google

_is_google_antigravity_installed() {
  [ -e $APP_PLATFORM_BIN_PATH/antigravity ]
}

_get_installed_antigravity_version() {
  local installed_antigravity_version=$(jq -r '.ideVersion' $GOOGLE_ANTIGRAVITY_INSTALL_PATH/Antigravity/resources/app/product.json)
  [ -z "$installed_antigravity_version" ] && {
    if [ -e "$GOOGLE_ANTIGRAVITY_INSTALL_PATH/Antigravity/bin/antigravity" ]; then
      installed_antigravity_version=$("$GOOGLE_ANTIGRAVITY_INSTALL_PATH/Antigravity/bin/antigravity" --version 2>/dev/null | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+' | head -1)
    fi
  }

  printf '%s' "$installed_antigravity_version"
}

_get_latest_antigravity_version() {
  local antigravity_latest_info=$(curl -sL 'https://antigravity-auto-updater-974169037036.us-central1.run.app/releases' | jq -r '.[0] | {version, execution_id}')

  antigravity_latest_version=$(printf '%s' "$antigravity_latest_info" | jq -r '.version')
  antigravity_latest_execution_id=$(printf '%s' "$antigravity_latest_info" | jq -r '.execution_id')
}

_is_antigravity_latest_version() {
  local installed_version
  
  installed_version=$(_get_installed_antigravity_version)
  [ -z "$installed_version" ] && return 1
  
  log_debug "installed version: $installed_version, latest version: $antigravity_latest_version"
  
  [ "$installed_version" = "$antigravity_latest_version" ]
}

_install_google_antigravity() {
  log_detail "installing Antigravity version: $antigravity_latest_version"
  
  _download_fetch "https://edgedl.me.gvt1.com/edgedl/release2/j0qc3/antigravity/stable/${antigravity_latest_version}-${antigravity_latest_execution_id}/linux-x64/Antigravity.tar.gz" Antigravity-$antigravity_latest_version-$antigravity_latest_execution_id.tar.gz
  clean=1 _extract_extract "$download_file" "$GOOGLE_ANTIGRAVITY_INSTALL_PATH"

  ln -sf "$GOOGLE_ANTIGRAVITY_INSTALL_PATH/Antigravity/bin/antigravity" "$APP_PLATFORM_BIN_PATH/antigravity"
}

case $APP_PLATFORM_SUB_PLATFORM in
  Arch | CachyOS)
      _get_latest_antigravity_version
      if ! _is_google_antigravity_installed; then
        log_detail "installing Antigravity"
        _install_google_antigravity
      elif ! _is_antigravity_latest_version; then
        log_detail "updating Antigravity"
        _install_google_antigravity
      else
        log_detail "antigravity is up to date"
      fi
      ;;
  *)
      log_warn "use platform package: $APP_PLATFORM_SUB_PLATFORM"
      ;;
esac