#!/bin/sh

cfg feature:.
cfg .


_vscode_install_extensions() {
	if [ -z "$feature_antigravity_extensions" ]; then
		log_warn "feature_antigravity_extensions is empty"
		return 1
	fi

	local normal_user
	for normal_user in $(getent group wheel | cut -d: -f4); do
		sudo_user=$normal_user
		local vscode_extension
		for vscode_extension in $feature_antigravity_extensions; do
			sudo_run $conf_dev_antigravity_executable --install-extension $vscode_extension
		done
	done
}

_vscode_install_extensions
