lib ssh.sh

_SETUP_GIT() {
	mkdir -p $(dirname $_CONF_OS_INSTALLER_SYSTEM_IDENTIFICATION)


	_prepare_ssh_conf $HOME $USER

	_git_setup $_CONF_OS_INSTALLER_SYSTEM_GIT $OS_INSTALLER_SYSTEM_WORKSPACE $_CONF_OS_INSTALLER_SYSTEM_NAME -b $_CONF_OS_INSTALLER_SYSTEM_REF

	cd $OS_INSTALLER_SYSTEM_WORKSPACE

	_git_write_system

	_SYSTEM_HASH=$(git rev-parse HEAD)
}

_git_write_system() {
	printf '%s\n' $_CONF_OS_INSTALLER_SYSTEM_NAME >$_CONF_OS_INSTALLER_SYSTEM_IDENTIFICATION
	git branch --no-color --show-current >>$_CONF_OS_INSTALLER_SYSTEM_IDENTIFICATION
	printf '%s\n' $_CONF_OS_INSTALLER_SYSTEM_GIT >>$_CONF_OS_INSTALLER_SYSTEM_IDENTIFICATION
	git ls-remote $_CONF_OS_INSTALLER_SYSTEM_GIT -b $_CONF_OS_INSTALLER_SYSTEM_BRANCH | grep "ref/heads/$_CONF_OS_INSTALLER_SYSTEM_BRANCH" | awk {'print$1'} >>$_CONF_OS_INSTALLER_SYSTEM_IDENTIFICATION

	printf 'Provision Date: %s\n' "$(date)" >>$_CONF_OS_INSTALLER_SYSTEM_IDENTIFICATION
}

