#!/bin/sh

lib net/download.sh
lib extract.sh

randoop_version=4.3.2

_install_randoop() {
    _download_fetch https://github.com/randoop/randoop/releases/download/v${randoop_version}/randoop-${randoop_version}.zip

    randoop_contents=$(_mktemp_options=d _mktemp_mktemp)
    exit_defer _cleanup_randoop
    _extract_extract $download_file $randoop_contents

    download_file=$randoop_contents/randoop-${randoop_version}/randoop-all-${randoop_version}.jar
    _download_install_file __LIBRARY_PATH__/__APPLICATION_NAME__/tools/randoop-all.jar
}

_cleanup_randoop() {
    rm -rf $randoop_contents
}

_install_randoop
