#!/bin/sh

lib time.sh

_CF_TIMEOUT=30

_cf_setup() {
  [ -z "$INTERACTIVE" ] && {
    _WARN "non-interactive, unable to configure cf"
    return 1
  }

  _require "$_CONF_DEV_CF_CLI_API_URL" _CONF_DEV_CF_CLI_API_URL
  _require "$_CONF_DEV_CF_CLI_USERNAME" _CONF_DEV_CF_CLI_USERNAME
  _require "$_CONF_DEV_CF_CLI_ORG" _CONF_DEV_CF_CLI_ORG
  _require "$_CONF_DEV_CF_CLI_SPACE" _CONF_DEV_CF_CLI_SPACE

  _WARN "Please enter your CF password ($_CONF_DEV_CF_CLI_USERNAME):"
  _timeout $_CF_TIMEOUT "Configuring CF - login" $_SUDO_NORMAL_USER_CMD cf login -a $_CONF_DEV_CF_CLI_API_URL -u $_CONF_DEV_CF_CLI_USERNAME -o $_CONF_DEV_CF_CLI_ORG -s $_CONF_DEV_CF_CLI_SPACE
}

which cf >/dev/null 2>&1 && _cf_setup
