#!/bin/sh

cfg feature:.

VENV_PATH=$(dirname $conf_dev_detect_secrets_venv)

_detect_secrets_venv_install() {
    sudo_run mkdir -p $VENV_PATH
    sudo_run chown -R $USER: $VENV_PATH

    python -m venv $conf_dev_detect_secrets_venv
    . $conf_dev_detect_secrets_venv/bin/activate
    pip install $conf_dev_detect_secrets_python_artifact

    deactivate

    sudo_run chown -R root: $conf_dev_detect_secrets_venv
}

_detect_secrets_venv_exists() {
    [ ! -e $conf_dev_detect_secrets_venv/bin/activate ] && return 1

    [ -e $conf_dev_detect_secrets_venv/bin/detect-secrets ]
 }
 
_detect_secrets_venv_exists || _detect_secrets_venv_install
