_is_latest() {
	[ ! -e $_INSTALL_LIBRARY_PATH/$1/.metadata ] && return 1

	_INSTALLED_APPLICATION_GIT_URL=$(grep _APPLICATION_GIT_URL $_INSTALL_LIBRARY_PATH/$1/.metadata 2>/dev/null | cut -f2 -d= | tr -d '"')
	_LATEST_APPLICATION_VERSION=$_TARGET_APPLICATION_VERSION
	_INSTALLED_APPLICATION_VERSION=$(grep _APPLICATION_VERSION $_INSTALL_LIBRARY_PATH/$1/.metadata 2>/dev/null | cut -f2 -d= | tr -d '"')

	[ "$_LATEST_APPLICATION_VERSION" = "$_INSTALLED_APPLICATION_VERSION" ]
}
