#!/bin/sh

lib io/write.sh

_LATEST_JDK=$(find /usr/local -maxdepth 1 -type d -name 'openjdk*' ! -name 'openjdk8' | sort -h | tail -1)
_JAVA_VERSION=$(printf '%s' "$_LATEST_JDK" | sed -e 's/^.*openjdk//')

_INFO "Updating Java Home to JDK$_JAVA_VERSION"

$_SUDO_CMD $_CONF_GNU_SED -i 's/^JAVA_HOME=/# JAVA_HOME=/' /usr/local/etc/javavm_opts.conf
printf 'JAVA_HOME=%s\n'  "$_LATEST_JDK" | _append /usr/local/etc/javavm_opts.conf
