_OPENRC_SERVICE_INSTALL() {
	rc-service add "$@"
}

_OPENRC_SERVICE_UNINSTALL() {
	rc-service del "$@"
}

_SYSTEMD_SERVICE_INSTALL() {
	systemctl enable "$@"
}

_SYSTEMD_SERVICE_UNINSTALL() {
	systemctl disable "$@"
}

_SERVICE_IS_FILE() {
	return 1
}

_SERVICE_INSTALL() {
	_${_CONF_LINUX_SERVICE_PROVIDER}_SERVICE_INSTALL "$@"
}

_SERVICE_UNINSTALL() {
	_${_CONF_LINUX_SERVICE_PROVIDER}_SERVICE_UNINSTALL "$@"
}
